apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Bal-Gopal/hello-world.git"
    path: "k8s"
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
